Anton S. homework_16 done
eugene-okulik/Anton pull request #29
Opened 2024-01-10 22:38 UTC by s3riousss

Отредактировал файл с домашним заданием в уроке 15 согласно комментариям

В уроке 16 не совсем понял:
_В результате сравнения, если обнаружится, что каких-то данных, которые есть в файле, нет в базе данных, распечатайте каких данных не хватает в базе._
Имеется ввиду, распечатать прям отдельно данные которых нет в бд или достаточно всю строку из файла?

2024-01-10 22:40 UTC, s3riousss commented
All checks have failed

тут я что-то не так наделал или нет?
![Снимок экрана 2024-01-10 233931](https://github.com/eugene-okulik/Anton/assets/152338007/c0ff9dda-3bcd-4273-9615-f9349879a2d8)

2024-01-12 07:50 UTC, eugene-okulik commented
> Отредактировал файл с домашним заданием в уроке 15 согласно комментариям
> 
> В уроке 16 не совсем понял: _В результате сравнения, если обнаружится, что каких-то данных, которые есть в файле, нет в базе данных, распечатайте каких данных не хватает в базе._ Имеется ввиду, распечатать прям отдельно данные которых нет в бд или достаточно всю строку из файла?

Достаточно строку из файла.

2024-01-12 07:52 UTC, eugene-okulik commented
> All checks have failed
> 
> тут я что-то не так наделал или нет? ![Снимок экрана 2024-01-10 233931](https://private-user-images.githubusercontent.com/152338007/295733535-c0ff9dda-3bcd-4273-9615-f9349879a2d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDYxODYsIm5iZiI6MTcwNTA0NTg4NiwicGF0aCI6Ii8xNTIzMzgwMDcvMjk1NzMzNTM1LWMwZmY5ZGRhLTNiY2QtNDI3My05NjE1LWY5MzQ5ODc5YTJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzUxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGFmYjdkODdiZTljYmIxOGVlNWZkZDViMjFhYTcwNzg0YWQ0ZDk5YjY3NjdjMGI0YjM5YzIyMWQxOGE3NDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._mU01xGUDDat0cPbOQ4OzAV3Wi9YSX6_Cxt6op7yBnI)

Оно тебе говорит, что в указанных строчках у тебя есть пробел в конце строки, который Линту не нравится

2024-01-12 07:58 UTC, eugene-okulik requested changes
В общем, разберись с тем, на что Линт ругается  
и еще подключение к базе ты забыл закрыть  
Остальное - хорошо

2024-01-12 07:58 UTC, eugene-okulik commented on homework/anton_sklepkovich/lesson_16/task.py
> +            print(f'Полная строка со студентом из файла: {row}')
Можно было и без этого первого ифа, в целом

2024-01-12 08:59 UTC, s3riousss commented
Добавил закрытие коннекта с базой и проверка lint пройдена

2024-01-12 09:01 UTC, s3riousss commented on homework/anton_sklepkovich/lesson_16/task.py
> +            print(f'Полная строка со студентом из файла: {row}')
тут если уберу if то логика реализации  поменяется. Так как я отталкивался от того, что если студента совсем нет то и смысла остальные значения искать в бд нет

2024-01-14 11:18 UTC, eugene-okulik commented on homework/anton_sklepkovich/lesson_16/task.py
> +            print(f'Полная строка со студентом из файла: {row}')
Чисто по логике программы, нет особого смысла делать это двумя запросами. Можно одним. И имеющийся студент без дополнительных данных и отсутствующий студент - это, по сути, одно и то же - отсутствие данных из файла в базе.

2024-01-14 11:24 UTC, eugene-okulik approved these changes

2024-01-14 11:24 UTC, merged